### ISSUE TITLE
Only even years

### ISSUE THREAD

**Issue by mslucash** [LANDIS-II-Foundation/Extension-Base-Hurricane#1]
For some reason, hurricanes only occur in even years. In 10 scenarios * 50 years (n=500), there were NO hurricanes in odd years.

**Comment by rmscheller** [comment]
I see from GitHub that the Timestep = 2.  https://github.com/LANDIS-II-Foundation/Project-Fort-Bragg-NC/blob/master/Model%20Inputs/Hurricane%20data/base-hurricane.txt

I have no idea why.
