### ISSUE TITLE
Hurricane summary log empty

### ISSUE THREAD

**Issue by TinaGM** [LANDIS-II-Foundation/Extension-Base-Hurricane#2]
When running this version of Base Hurricane, the hurricane summary log shows zero Total Sites and zero Number of Events for the entire model run while the hurricane events log shows that hurricanes, including some impacting my study area, have occurred.

**Comment by rmscheller** [comment]
So, this is sort of fixed.  The number of events should now reflect the number of hurricanes that hit the area.  I removed total-number-of-sites, as every hurricane affects the ENTIRE landscape.  Is there other information you would like to see in the summary log?

**Comment by TinaGM** [comment]
Not that I can think of, so I'll go ahead and close the issue.
