### ISSUE TITLE
Altering max sustained wind speed by general stand structural characteristics

### ISSUE THREAD

**Issue by jameslamping** [LANDIS-II-Foundation/Extension-Base-Hurricane#4]
The hurricane extension currently only uses species age as a way to parameterize for an individual species susceptibility to wind. Forest structure can also play a role in a stands overall susceptibility to wind disturbance. I was wondering if we could use the outputs from the Cohort Statistics Output extension as an optional way to alter the max sustained wind speed in a given cell? The idea would be an optional table that determines a percentage decrease of MSW based off of the SiteAgeStat "Richness" stat. If it is possible, allow it to use any statistical output from this extension so it can be used for other use cases. Thank you!

**Comment by rmscheller** [comment]
James,
I updates the CSO extension to 'register' the variable Output.AgeRichness with the Core.  The hurricane extension can now use that information if the extension is running and that variable is calculated.  How should the hurricane extension use that information?

Any additional such variables would also need to be explicitly registered in this manner.  Similarly, the hurricane extension would have to have explicit instructions how to use that data.

**Comment by jameslamping** [comment]
Perfect! Thank you! For now I think we should stick with Richness and see how it works. I think that the best method to determine what hurricane should do is a simple table that allows us to give a range of “Richness” values that we can then apply a certain percentage decrease of maximum sustained wind speed calculated from the hurricane extension.

Something like:
![Screenshot 2023-04-18 at 2 40 29 PM](https://user-images.githubusercontent.com/40306849/232911604-35a1f11f-5d3f-43bc-9531-29288dbf20bb.png)


>> Statistic Range                   Percent decrease
>>—————————————————————
	3-5						10
	6-7						25

I am still looking into seeing if I can find good values to see if I can come up with good percentages, but I think I might just see how these percentages affect modeled disturbance and see if it looks like what has been published.

**Comment by rmscheller** [comment]
James, the latest version is now ready for your testing.  Pair this with a vintage Output Cohort Statistics v3.0.3.  I used dummy data in the windReductions table.

**Comment by rmscheller** [comment]
James,
Could you add the 'removed biomass' issue?  I can't add you to an issue if I make it myself.
